server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false # Lazy loading 방지, 성능 최적화
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}