spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/board?options=-c%20TimeZone=Asia/Seoul&ssl=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true

notification:
  discord:
    webhook-urls:
      info: ${DISCORD_WEBHOOK_INFO_URL}
      error: ${DISCORD_WEBHOOK_ERROR_URL}