spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/board?options=-c%20TimeZone=Asia/Seoul&ssl=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  file:
    name: /var/logs/app.log
